### PR TITLE
Update openshift

### PR DESCRIPTION
**Pull request by kadel**
After some Godeps.json hacking in OpenShift I was able to update Henge to latest OpenShift ([11c7ed066aa65ec80dd34446f86bce9a285400f8](https://github.com/openshift/origin/tree/11c7ed066aa65ec80dd34446f86bce9a285400f8))

### CODE REVIEW

**Comment by kadel** [comment]
this should depricate https://github.com/redhat-developer/henge/pull/18 because this fix should be already in OpenShift

**Comment by surajssd** [comment]
@kadel LGTM, #18 we still need to add code here https://github.com/redhat-developer/henge/pull/18/files#diff-0e84ec7c43751b982f29dbc4fa65927dR53

**Comment by kadel** [comment]
We are still using libcompose from openshift, so only thing that wee need to add are 3 lines to `openshift/generate.go`
```go
if err := project.AddEnvironmentLookUp(context); err != nil {
   return nil, err
 }
```

is it right?

**Comment by surajssd** [comment]
@kadel yes true!

**Comment by kadel** [comment]
great, I'm going to merge this than. 
Can you than please modify #18 so it only contains changes to `oenshift/generate.go`?

**Comment by surajssd** [comment]
@kadel sure!

**Comment by kadel** [comment]
thank you @surajssd

**Pull request merged**
