### PR TITLE
Add project goals to readme

### PR DESCRIPTION
**Pull request by kadel**

### CODE REVIEW

**Comment by pradeepto** [comment]
@dustymabe @pmuir @rtnpro Would be awesome to have some eyeballs on this from you folks.

**Comment by rtnpro** [comment]
:+1: LGTM

**Comment by pmuir** [comment]
I would modify the third point to be a bit more generic such as "can be used as a library or service with another front end e.g. oc, kubectl, a web app or an IDE.

**Comment by kadel** [comment]
I Updated commit according to @pmuir suggestion

**Pull request merged**
